/** US Army MOS / CMF codes for admin assignment (reference; verify against current DA guidance). */
export type ArmyMosOption = { code: string; title: string };
export const US_ARMY_MOS_OPTIONS: ArmyMosOption[] = [
  { code: "00", title: "Not specified / pending classification" },
  { code: "09L", title: "Interpreter / Translator" },
  { code: "11A", title: "Infantry Officer" },
  { code: "11B", title: "Infantryman" },
  { code: "11C", title: "Indirect Fire Infantryman" },
  { code: "11X", title: "Infantry enlistment option" },
  { code: "11Z", title: "Infantry Senior Sergeant" },
  { code: "12A", title: "Engineer Officer" },
  { code: "12B", title: "Combat Engineer" },
  { code: "12C", title: "Bridge Crewmember" },
  { code: "12D", title: "Diver" },
  { code: "12G", title: "Geospatial Engineer" },
  { code: "12H", title: "Construction Engineering Supervisor" },
  { code: "12K", title: "Plumber" },
  { code: "12M", title: "Firefighter" },
  { code: "12N", title: "Horizontal Construction Engineer" },
  { code: "12P", title: "Prime Power Production Specialist" },
  { code: "12Q", title: "Power Line Distribution Specialist" },
  { code: "12R", title: "Interior Electrician" },
  { code: "12T", title: "Technical Engineer" },
  { code: "12V", title: "Concrete and Asphalt Equipment Operator" },
  { code: "12W", title: "Carpentry and Masonry Specialist" },
  { code: "12Y", title: "Geospatial Engineer (Enlisted)" },
  { code: "13A", title: "Field Artillery Officer" },
  { code: "13B", title: "Cannon Crewmember" },
  { code: "13F", title: "Fire Support Specialist" },
  { code: "13J", title: "Automated Field Artillery Tactical Data Specialist" },
  { code: "13M", title: "Multiple Launch Rocket System Crewmember" },
  { code: "13R", title: "Field Artillery Radar Operator" },
  { code: "13T", title: "Field Artillery Automated Tactical Data System Specialist" },
  { code: "13Z", title: "Field Artillery Senior Sergeant" },
  { code: "14A", title: "Air Defense Artillery Officer" },
  { code: "14E", title: "Patriot Fire Control Enhanced Operator/Maintainer" },
  { code: "14G", title: "Air Defense Battle Management System Operator" },
  { code: "14H", title: "Air Defense Enhanced Early Warning System Operator" },
  { code: "14P", title: "Air and Missile Defense Crewmember" },
  { code: "14S", title: "Air Defense Artillery Avenger Crewmember" },
  { code: "14T", title: "Patriot Launching Station Operator/Maintainer" },
  { code: "15A", title: "Aviation Officer" },
  { code: "15B", title: "Aircraft Powerplant Repairer" },
  { code: "15C", title: "MQ-1 Gray Eagle Operator" },
  { code: "15D", title: "Avionics Systems Repairer" },
  { code: "15E", title: "Unmanned Aircraft Systems Repairer" },
  { code: "15F", title: "Aircraft Electrician" },
  { code: "15G", title: "Aircraft Structural Repairer" },
  { code: "15H", title: "Aircraft Pneudraulics Repairer" },
  { code: "15J", title: "OH-58 Armament/Electrical/Avionics Repairer" },
  { code: "15M", title: "MQ-9 Maintainer" },
  { code: "15N", title: "Avionic Mechanic" },
  { code: "15P", title: "Aviation Operations Specialist" },
  { code: "15Q", title: "Air Traffic Control Operator" },
  { code: "15R", title: "AH-64 Attack Helicopter Repairer" },
  { code: "15S", title: "OH-58 Helicopter Repairer" },
  { code: "15T", title: "UH-60 Helicopter Repairer" },
  { code: "15U", title: "CH-47 Helicopter Repairer" },
  { code: "15V", title: "Observation/Scout Helicopter Repairer" },
  { code: "15W", title: "Unmanned Aircraft Systems Operator" },
  { code: "15X", title: "AH-64 Armament/Electrical/Avionics Repairer" },
  { code: "15Y", title: "AH-64 Armament Repairer" },
  { code: "15Z", title: "Aviation Maintenance Senior Sergeant" },
  { code: "17C", title: "Cyber Operations Specialist" },
  { code: "17E", title: "Electronic Warfare Specialist" },
  { code: "18A", title: "Special Forces Officer" },
  { code: "18B", title: "Special Forces Weapons Sergeant" },
  { code: "18C", title: "Special Forces Engineer Sergeant" },
  { code: "18D", title: "Special Forces Medical Sergeant" },
  { code: "18E", title: "Special Forces Communications Sergeant" },
  { code: "18F", title: "Special Forces Intelligence Sergeant" },
  { code: "18X", title: "Special Forces Candidate" },
  { code: "18Z", title: "Special Forces Senior Sergeant" },
  { code: "19A", title: "Armor Officer" },
  { code: "19C", title: "Cavalry Scout" },
  { code: "19D", title: "Cavalry Scout" },
  { code: "19K", title: "M1 Armor Crewman" },
  { code: "19Z", title: "Armor Senior Sergeant" },
  { code: "25A", title: "Signal Officer" },
  { code: "25B", title: "Information Technology Specialist" },
  { code: "25C", title: "Radio Operator/Maintainer" },
  { code: "25D", title: "Cyber Network Defender" },
  { code: "25E", title: "Electromagnetic Warfare Technician" },
  { code: "25H", title: "Network Communication Systems Specialist" },
  { code: "25L", title: "Cable Systems Installer/Maintainer" },
  { code: "25M", title: "Multimedia Illustrator" },
  { code: "25N", title: "Nodal Network Systems Operator/Maintainer" },
  { code: "25P", title: "Microwave Systems Operator/Maintainer" },
  { code: "25Q", title: "Multichannel Transmission Systems Operator" },
  { code: "25R", title: "Visual Information Equipment Operator/Maintainer" },
  { code: "25S", title: "Satellite Communication Systems Operator" },
  { code: "25T", title: "Satellite/Microwave Systems Chief" },
  { code: "25U", title: "Signal Support Systems Specialist" },
  { code: "25V", title: "Combat Documentation/Production Specialist" },
  { code: "25W", title: "Telecommunications Operations Chief" },
  { code: "25X", title: "Chief Signal NCO" },
  { code: "25Z", title: "Visual Information Operations Chief" },
  { code: "27A", title: "Judge Advocate General Officer" },
  { code: "27B", title: "Military Judge" },
  { code: "27D", title: "Paralegal Specialist" },
  { code: "29E", title: "Electronic Warfare Specialist" },
  { code: "31A", title: "Military Police Officer" },
  { code: "31B", title: "Military Police" },
  { code: "31D", title: "CID Special Agent" },
  { code: "31E", title: "Internment/Resettlement Specialist" },
  { code: "31K", title: "Military Working Dog Handler" },
  { code: "35A", title: "Military Intelligence Officer" },
  { code: "35D", title: "All-Source Intelligence Officer" },
  { code: "35F", title: "Intelligence Analyst" },
  { code: "35G", title: "Geospatial Intelligence Imagery Analyst" },
  { code: "35L", title: "Counter Intelligence Agent" },
  { code: "35M", title: "Human Intelligence Collector" },
  { code: "35N", title: "Signals Intelligence Analyst" },
  { code: "35P", title: "Cryptologic Linguist" },
  { code: "35Q", title: "Cryptologic Network Warfare Specialist" },
  { code: "35S", title: "Signals Collector/Analyst" },
  { code: "35T", title: "Military Intelligence Systems Maintainer" },
  { code: "35X", title: "Intelligence Senior Sergeant/Chief" },
  { code: "36A", title: "Financial Management Officer" },
  { code: "36B", title: "Financial Management Technician" },
  { code: "37A", title: "Psychological Operations Officer" },
  { code: "37F", title: "Psychological Operations Specialist" },
  { code: "38A", title: "Civil Affairs Officer" },
  { code: "38B", title: "Civil Affairs Specialist" },
  { code: "40A", title: "Space Operations Officer" },
  { code: "42A", title: "Human Resources Specialist" },
  { code: "42H", title: "Senior Human Resources Officer" },
  { code: "42R", title: "Army Band" },
  { code: "42S", title: "Special Band Musician" },
  { code: "43A", title: "Human Resources Officer" },
  { code: "44A", title: "Finance Officer" },
  { code: "44B", title: "Financial Analyst" },
  { code: "44C", title: "Financial Management Technician" },
  { code: "46A", title: "Public Affairs Officer" },
  { code: "46Q", title: "Public Affairs Specialist" },
  { code: "46R", title: "Broadcast Journalist" },
  { code: "46S", title: "Public Affairs Mass Communication Specialist" },
  { code: "46Z", title: "Chief Public Affairs NCO" },
  { code: "56A", title: "Chaplain" },
  { code: "56M", title: "Chaplain Assistant" },
  { code: "59A", title: "Strategist" },
  { code: "60A", title: "Medical Corps Officer" },
  { code: "62A", title: "Medical Service Corps Officer" },
  { code: "63A", title: "Dental Corps Officer" },
  { code: "64A", title: "Veterinary Corps Officer" },
  { code: "65B", title: "Physical Therapist" },
  { code: "65C", title: "Physician Assistant" },
  { code: "66C", title: "Practical Nursing Specialist" },
  { code: "66W", title: "Medical/Surgical Nurse" },
  { code: "67C", title: "Preventive Medicine Specialist" },
  { code: "67D", title: "Behavioral Health Specialist" },
  { code: "67G", title: "Patient Administration Specialist" },
  { code: "68A", title: "Biomedical Equipment Specialist" },
  { code: "68B", title: "Orthopedic Specialist" },
  { code: "68C", title: "Practical Nursing Specialist" },
  { code: "68D", title: "Dental Specialist" },
  { code: "68F", title: "Physical Therapy Specialist" },
  { code: "68G", title: "Patient Administration Specialist" },
  { code: "68J", title: "Medical Logistics Specialist" },
  { code: "68K", title: "Medical Laboratory Specialist" },
  { code: "68L", title: "Occupational Therapy Specialist" },
  { code: "68M", title: "Nutrition Care Specialist" },
  { code: "68N", title: "Cardiovascular Specialist" },
  { code: "68P", title: "Radiology Specialist" },
  { code: "68Q", title: "Pharmacy Specialist" },
  { code: "68R", title: "Medical Laboratory Specialist" },
  { code: "68S", title: "Preventive Medicine Specialist" },
  { code: "68T", title: "Animal Care Specialist" },
  { code: "68W", title: "Combat Medic Specialist" },
  { code: "68X", title: "Behavioral Health Specialist" },
  { code: "68Y", title: "Eye Specialist" },
  { code: "74A", title: "CBRN Officer" },
  { code: "74D", title: "CBRN Specialist" },
  { code: "79R", title: "Recruiter" },
  { code: "79S", title: "Career Counselor" },
  { code: "79T", title: "Recruiting and Retention NCO" },
  { code: "88A", title: "Transportation Corps Officer" },
  { code: "88H", title: "Cargo Specialist" },
  { code: "88K", title: "Watercraft Operator" },
  { code: "88L", title: "Watercraft Engineer" },
  { code: "88M", title: "Motor Transport Operator" },
  { code: "88N", title: "Transportation Management Coordinator" },
  { code: "88P", title: "Railway Equipment Repairer" },
  { code: "88T", title: "Railway Section Repairer" },
  { code: "88U", title: "Railway Operations Crewmember" },
  { code: "89A", title: "Ammunition Stock Control and Accounting Specialist" },
  { code: "89B", title: "Ammunition Specialist" },
  { code: "89D", title: "Explosive Ordnance Disposal Specialist" },
  { code: "90A", title: "Logistics Corps Officer" },
  { code: "91A", title: "Medical Logistics Officer" },
  { code: "91B", title: "Wheeled Vehicle Mechanic" },
  { code: "91D", title: "Power Generation Equipment Repairer" },
  { code: "91E", title: "Allied Trade Specialist" },
  { code: "91F", title: "Small Arms/Towed Artillery Repairer" },
  { code: "91G", title: "Fire Control Repairer" },
  { code: "91H", title: "Track Vehicle Repairer" },
  { code: "91J", title: "Quartermaster and Chemical Equipment Repairer" },
  { code: "91L", title: "Construction Equipment Repairer" },
  { code: "91M", title: "Bradley Fighting Vehicle System Maintainer" },
  { code: "91P", title: "Artillery Mechanic" },
  { code: "91S", title: "Stryker Systems Maintainer" },
  { code: "91X", title: "Maintenance Supervisor" },
  { code: "91Z", title: "Mechanical Maintenance Supervisor" },
  { code: "92A", title: "Automated Logistical Specialist" },
  { code: "92F", title: "Petroleum Supply Specialist" },
  { code: "92G", title: "Culinary Specialist" },
  { code: "92L", title: "Petroleum Laboratory Specialist" },
  { code: "92M", title: "Mortuary Affairs Specialist" },
  { code: "92R", title: "Parachute Rigger" },
  { code: "92S", title: "Shower/Laundry and Clothing Repair Specialist" },
  { code: "92W", title: "Water Treatment Specialist" },
  { code: "92Y", title: "Unit Supply Specialist" },
  { code: "92Z", title: "Senior Supply Sergeant" },
  { code: "94D", title: "Electronic Maintenance Chief" },
  { code: "94E", title: "Radio and Communications Security Repairer" },
  { code: "94F", title: "Computer/Detection Systems Repairer" },
  { code: "94H", title: "Test Measurement and Diagnostic Equipment Maintenance Support Specialist" },
  { code: "94M", title: "Radar Repairer" },
  { code: "94P", title: "Multiple Launch Rocket System Repairer" },
  { code: "94R", title: "Avionic and Survivability Equipment Repairer" },
  { code: "94S", title: "Patriot System Repairer" },
  { code: "94T", title: "Missile Repairer" },
  { code: "94W", title: "Electronic Maintenance Chief" },
  { code: "94Y", title: "Integrated Family of Test Equipment Operator/Maintainer" },
  { code: "120A", title: "Aviation Logistics Officer" },
  { code: "140A", title: "Air Defense Artillery Officer" },
  { code: "150A", title: "Aviation Warrant Officer" },
  { code: "153A", title: "Rotary Wing Aviator" },
  { code: "154A", title: "Fixed Wing Aviator" },
  { code: "180A", title: "Special Forces Warrant Officer" },
  { code: "420A", title: "Human Resources Technician" },
  { code: "882A", title: "Mobility Officer" },
  { code: "920A", title: "Property Accounting Technician" },
  { code: "920B", title: "Supply Systems Technician" },
];
export const US_ARMY_MOS_BY_CODE = new Map(US_ARMY_MOS_OPTIONS.map((o) => [o.code, o.title]));
